steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:19.03.9'
  - '--file=Dockerfile-19.03.9'
  - '.'
  id: '19.03.9'
